[project]
name = "funfile"
description = "funfile"
readme = "README.md"
version = "1.0.19"
requires-python = ">=3.7"
dependencies = [ "funlog>=1.0.0", "tqdm>=4.66.5",]
[[project.authors]]
name = "niuliangtao"
email = "farfarfun@qq.com"

[tool.setuptools]
license-files = []
