[project]
name = "funfile"
description = "funfile"
readme = "README.md"
version = "1.0.18"
requires-python = ">=3.7"
dependencies = [ "funlog>=0.1.7", "tqdm>=4.66.5",]
[[project.authors]]
name = "niuliangtao"
email = "farfarfun@qq.com"

[tool.setuptools]
license-files = []
